# Generated by Django 5.1.4 on 2025-01-21 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThreeModule_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.IntegerField(null=True)),
                ('Phone_number', models.CharField(max_length=255, null=True)),
                ('Course', models.CharField(max_length=255, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
